# Generated by Django 4.2.7 on 2024-05-01 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfApp', '0002_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
