# Generated by Django 4.2.7 on 2024-05-01 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfApp', '0003_emission_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('subject', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=300)),
                ('experts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cfApp.experts')),
            ],
        ),
    ]
