# Generated by Django 4.2.7 on 2024-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfApp', '0004_tips'),
    ]

    operations = [
        migrations.AddField(
            model_name='tips',
            name='proof',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
