# Generated by Django 4.2.7 on 2024-05-01 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfApp', '0005_tips_proof'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tips',
            old_name='proof',
            new_name='image',
        ),
    ]
