# Generated by Django 5.0.6 on 2024-07-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfApp', '0007_emission_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='emission',
            name='no_of_devices',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
